### ISSUE TITLE
Overseerr

### ISSUE THREAD

**Issue by Famku** [diogovalentte/homarr-iframes#2]
Hi,

how does this work with Overseerr?

Or this only works with the predefinate apps?

**Comment by diogovalentte** [comment]
Hi, this works only with predefined apps, I manually create the iframes.

> how does this work with Overseerr?

Do you want an iframe to show your media requests on Overseerr? If so, you can use the "Media Requests" built-in widget.

**Comment by Famku** [comment]
I wanted to use Overseerr requests for homepage (https://github.com/gethomepage/homepage) in an iframe 

Is this possible?

**Comment by Famku** [comment]
Maybe you reach more people if you offer this not just for homarr user

**Comment by diogovalentte** [comment]
So, you want an iframe with your Overseerr requests, like the image below, so that you can use it on homepage?

![image](https://github.com/diogovalentte/homarr-iframes/assets/49578155/653e56e4-84c6-4d04-a463-0c6dcc26339a)

**Comment by Famku** [comment]
Yes, I think this would be useful for more user

**Comment by diogovalentte** [comment]
Ok, I can do it. I'll comment here when it's done.

**Comment by Famku** [comment]
works fine, thanks for your work!

looking forward to see more apps

**Comment by Famku** [comment]
I told the homepage Discord community about your repo  - hopefully you receive more stars
