### ISSUE TITLE
Specify Project for Vikunja iFrame

### ISSUE THREAD

**Issue by minispalla** [diogovalentte/homarr-iframes#3]
Thanks for this project. I have been enjoying using the Vikunja iFrame inside of Homarr. 

I looked over the documentation to see if there is a way to have it only show tasks from a single project. Did I miss something along the way? 

I appreciate your time!

**Comment by diogovalentte** [comment]
Hi, there was no option to show tasks from a specific project, but I release a new version where you can filter by project ID. You can check the API docs to see how.

**Comment by minispalla** [comment]
This is awesome! Thank you for your help!
