### ISSUE TITLE
Issue with marking Vikunja tasks as done

### ISSUE THREAD

**Issue by minispalla** [diogovalentte/homarr-iframes#4]
Reviewing your documentation again, I noticed you could mark tasks as done through the iFrame for Vikunja. I set the API token as you described, but I get

```
curl -X 'PATCH' \
  'http://homarriframe.local/v1/iframe/vikunja/set_task_done?task_id=2428' \
  -H 'accept: application/json'

http://homarriframe.local/v1/iframe/vikunja/set_task_done?task_id=2428
```

```
400 Error: Bad Request
{
  "message": "task_id is required"
}
```

I also tried using an API token with complete access to my Vikunja instance, but it didn't work. I also made sure it was the correct task ID. 

`http://vikunja.local/tasks/2428`

If you would like any more information from me, please don't hesitate to let me know. 

I appreciate any help fixing it, and I appreciate your time.

**Comment by diogovalentte** [comment]
Hi, thanks for creating this issue, the API docs (and this request response) were outdated. I released a new version fixing it.

Instead of `task_id`, it's `taskId`.

**Comment by minispalla** [comment]
Thanks! I appreciate your time!
