### ISSUE TITLE
No image for Vikunja

### ISSUE THREAD

**Issue by J-C-Zeppeli-Gyro** [diogovalentte/homarr-iframes#5]
Hi,
![image](https://github.com/diogovalentte/homarr-iframes/assets/74025050/c5ee56bc-261c-4322-a27f-b888291da8a8)
![image](https://github.com/diogovalentte/homarr-iframes/assets/74025050/0fb1f8a7-d4af-428e-bbb8-08cc75e745d2)
I don't know if its temporarly or permament for them. I tried to change the image inside my container but no changes,
in /app/src/sources/vikunja/vikunja.go. In the web inspector I change the image to this:
![image](https://raw.githubusercontent.com/go-vikunja/vikunja/main/frontend/originalMedia/icons/icon-maskable.png)
That was the only that it worked well enough.

**Comment by diogovalentte** [comment]
Hi, thanks for opening this issue. I released a new version fixing it.

**Comment by J-C-Zeppeli-Gyro** [comment]
Thanks, much appreciated!
