### ISSUE TITLE
Media requests - Avatar url Jellyseer incorrect

### ISSUE THREAD

**Issue by martn263** [diogovalentte/homarr-iframes#6]
Description:
- An incorrect avatarurl  '/avatarproxy/<userid>'  is used without including the Jellyseer instance base url. 
- When the avarar image url can't be opened the alt text 'Requested By Avatar' appears.

Expected:
- The Jellyseer base url precedes the '/avatarproxy/<user_id>'. 
- No 'alt' text is shown if the avatar image could not be found. 

```
<img class="requested-by-avatar" src="/avatarproxy/<user_id>" alt="Requested By Avatar">
```
![media_request](https://github.com/user-attachments/assets/b85f41a9-abb1-490c-9b29-2e41e40c1d57)

Version: homarr-iframes v1.1.0, Jellyseer v2.1.0
Config used: 
- JELLYSEERR_ADDRESS: <jellyseerr_url>
- INTERNAL_JELLYSEERR_ADDRESS:<jellyseerr_url>
- JELLYSEERR_API_KEY: <api_key>

**Comment by diogovalentte** [comment]
Hi, thanks for pointing it out. Fixed in [v1.1.1](https://github.com/diogovalentte/homarr-iframes/releases/tag/v1.1.1), docker image already avaliable.
