### ISSUE TITLE
Vikunja background image

### ISSUE THREAD

**Issue by Famku** [diogovalentte/homarr-iframes#7]
Hi,

how to change the Vikunja background image?

I already changed it in vikunja.go in the container, but it wont change.

**Comment by diogovalentte** [comment]
Currently, the iframes' background image cannot be changed. Would you like to provide an image URL as the background image of the iframe, like using an environment variable or something like that?

**Comment by diogovalentte** [comment]
I added the `VIKUNJA_BACKGROUND_IMG_URL` environment variable in the latest [v1.2.0](https://github.com/diogovalentte/homarr-iframes/releases/tag/v1.2.0) version.

I also added the `background_position`, `background_size`, and `background_filter` query arguments to the Vikunja iframe to change the image CSS properties.

**Comment by Famku** [comment]
I will check it out.
Thanks for your quick handling

**Comment by Famku** [comment]
Unfortunately it doesn't work for me. I wanted to change the image with the vikunja Maybe you mean another image?

**Comment by diogovalentte** [comment]
I tried changing and it worked. It's not it what you wanted?

![image](https://github.com/user-attachments/assets/6c68506c-9615-4d68-a285-1b9c47c53df4)

**Comment by diogovalentte** [comment]
Any image URL should work, try this:
1. Make sure you updated the container to the newest version.
2. Make sure the environment variable is correctly being used. Maybe there is a special character that is causing a problem depending on how to you provide the environment variable.
3. Try this image, it's the same of my example above: https://images.pexels.com/photos/2071882/pexels-photo-2071882.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500

**Comment by Famku** [comment]
still doesn't work
here is my .env:

VIKUNJA_ADDRESS=******
INTERNAL_VIKUNJA_ADDRESS=******
VIKUNJA_TOKEN=********
VIKUNJA_BACKGROUND_IMG_URL=https://images.pexels.com/photos/2071882/pexels-photo-2071882.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500

do I need more?

**Comment by diogovalentte** [comment]
It should be right. Does it show the default vikunja image in the iframe or no background image?

**Comment by Famku** [comment]
I see the default image

`services:
  homarr-iframes:
    container_name: homarr-iframes
    image: ghcr.io/diogovalentte/homarr-iframes:latest
    user: 1000:1000
    environment:
      - TZ=${TZ:-UTC}
      - PORT=${PORT:-8080}
      
      - OVERSEERR_ADDRESS=${OVERSEERR_ADDRESS:-}
      - INTERNAL_OVERSEERR_ADDRESS=${INTERNAL_OVERSEERR_ADDRESS:-}
      - OVERSEERR_API_KEY=${OVERSEERR_API_KEY:-}
      
      - VIKUNJA_ADDRESS=${VIKUNJA_ADDRESS:-}
      - INTERNAL_VIKUNJA_ADDRESS=${INTERNAL_VIKUNJA_ADDRESS:-}
      - VIKUNJA_TOKEN=${VIKUNJA_TOKEN:-}

    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8080:8080
    restart: on-failure`

**Comment by Famku** [comment]
now it works 
thanks again
